// import type { Metadata } from "next";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { ReactNode } from "react";
import "../styles/globals.css";

// ! fontawesome 
import "@fortawesome/fontawesome-svg-core/styles";
import { config } from "@fortawesome/fontawesome-svg-core"
config.autoAddCss = false;

// ! font optimization
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/shared/Navbar";
import Providers from "../components/providers/Providers";
import { verifyToken } from "../features/auth/server/auth.actions";
import { CartState } from "../features/cart/store/cart.slice";
import { getLoggedUserCart } from "../features/cart/server/cart.actions";
import Footer from "../components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600"]
});

let carstate: CartState = {
  cartId: null,
  numOfCartItems: 0,
  totalCartPrice: 0,
  products: [],
  error: null,
  isLoading: false
}

export default async function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  const authValues = await verifyToken() //* {isAuthenticated: true ,userInfo}

  if (authValues.isAuthenticated) {
    try {
      const CartResponse = await getLoggedUserCart();
      
      carstate = {
        cartId: CartResponse.cartId,
        numOfCartItems: CartResponse.numOfCartItems,
        totalCartPrice: CartResponse.data.totalCartPrice,
        products: CartResponse.data.products,
        error: null,
        isLoading: false
      }
    } catch (error) {}
  }

  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased bg-gray-100`}>
        <Providers preloadedState={{ auth: authValues, cart: carstate }}>
          <Navbar />
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
